version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  redis:
    image: redis/redis-stack-server
    restart: always
    ports:
      - '${REDIS_DESKTOP_PORT}:${REDIS_PORT}'

volumes:
  db:
